### ISSUE TITLE
How do I get a build with tables embedded?

### ISSUE THREAD

**Issue by nrimsky** [reiner-dolp/liblouis-js#53]
I've tried compiling liblouis with emscripten, but how do I get a build that includes the tables in the js output as opposed to relying on external files?

I followed these instructions: https://github.com/liblouis/liblouis-js#compiling-the-latest-version-of-liblouis, adding `--embed-file tables` to the final command.

I found I had to delete the contents of the `man/Makefile.am` to get `emmake make` to work + I copied the `liblouis-js` repo inside of `liblouis` to get `--pre-js ./liblouis-js/inc/pre.js --post-js ./liblouis-js/inc/post.js` to reference the correct files.

The final output was a js build, however it did not contain the table data. (I want something like this: https://raw.githubusercontent.com/PaigeBraille/paige-web-app/main/www/js/build-tables-embeded-root-utf16.js that contains the table data as arrays in memory)

**Comment by pconerly** [comment]
Hi @nrimsky 

There were two different paths that worked for me:

### Github actions

The first way is kinda funky, by resurrecting some commented-out github actions:

You can look at my github action run here for Emscripten:
https://github.com/pconerly/liblouis/actions/runs/5384863958

The main changes I made were:
- Re-enable the emscripten build with tables
- Fixed the path of the tables folder (It was `/tables@/` some time ago, and it should be `/tables/`)

If you're going to do this a lot in your own fork of the repo, I'd recommend commenting-out the `macro.yml`, `check-format.yml`, and `scorecards.yml` workflows to save Actions minutes.

### Using the docker commands in the github actions

You could also do on your own machine, by using docker and the commands from the `emscripten.yml` file. Specifically:

```sh
docker pull dolp/liblouis-js-build-travis:1.37.3
docker run --rm -v $(pwd):/src dolp/liblouis-js-build-travis:1.37.3-64bit /bin/bash ".github/workflows/scripts/emscripten-build.sh"
```

You'll still need to fix the pathname of `/tables/` and un-comment the lines for building the tables. See this commit for an example: https://github.com/pconerly/liblouis/commit/24f700e09f4c1881ca981f382ffa04e27b70c420#diff-fa77dff7a815370064097fa138e03177b624798c60df8fcb2222fcb9529960e3

I found the "local-docker" strategy to be slower, but that's because I'm running on a M1 arm64 chip and I had to run the container in simulated mode. YMMV

**Comment by bertfrees** [comment]
Thanks @pconerly
